#!/usr/bin/env bash
# how to use an if statemnet in a while loop
x=1 
while [ $x -le 10 ]
do 
	if [ $x = 9 ]
	then
		echo "Best School"
		echo "Hi"
		x=$(( x+1 ))
	else 
		echo "Best School"
		x=$(( x+1 ))
	fi
done
