#!/usr/bin/env bash
# Let try adding iteration 
i=1
while [ $i -le 10 ]
do 
	if [ $i = 4 ]
	then
		echo "bad luck"
		i=$(( i + l ))
	elif [ $i = 8 ]
	then
		echo "good luck"
		i=$(( i + l ))
	else
		echo "Best School"
		i=$(( i + l ))
	fi
done
