#!/bin/bash
# lets display all the way to 10
x=1
while [ $x -le 20 ]
do
	case $NUMBER in
		"4")
			echo "4"
			echo "bad luck from China"
			;;
		"9")
		echo "9"
		echo "bad luck from Japan"
		;;
	"17")
		echo "17"
		echo "bad luck from Italy"
		;;
	"*")
		echo "$x"
		;;
esac
done
